#获取交换机基本信息
BasicInformation:
  # 获取交换机品牌的命令
  getBrandCommand: show version;display version
  # 获取交换机设备版本的关键字,默认关键字的下一位为要取的参数
  deviceVersion: Version
  # 获取交换机设备子版本的关键字,默认关键字的下一位为要取的参数,两个关键字之间以;分隔
  deviceSubversion: Release;Build;RELEASE SOFTWARE
  # 区分交换机还是路由器的标志  属性值开头并且包含数字
  routerFlag: NE

#OSPF
OSPF:
  # 命令
  command:
    #全部命令和参数支持精确匹配和模糊匹配，系统会优先执行精确匹配，然后执行模糊匹配。
    #格式为：品牌>型号>版本>子版本;如果为模糊匹配，请省略后续输入。例如：
    #输入为："H3C>s2152>5.20.99>1106："为精确匹配，如果输入为"H3C："即为模糊匹配
    #匹配精确度包含： "品牌>型号>版本>子版本"、"品牌>型号>版本"、"品牌>型号"、"品牌"、"品牌>*>版本"（）
    H3C: display ospf peer
    H3C>S2152: display ospf peer
    H3C>S2152>5.20.99: display ospf peer
    H3C>*>5.20.99: display ospf peer
    H3C>S2152>5.20.99>1106: display ospf peer

    HuaWei: display ospf peer brief
    Cisco: show ip ospf neighbor
    RuiJie: show ip ospf neighbor

  # neighborID、pri、state、deadTime、address、portNumber、BFDState
  # 这些属性是为了区分OSPF命令返回信息中的参数值
  # 邻居ID
  neighborID: Neighbor ID;Router ID
  # pri暂未使用，为占位列
  pri: Pri;
  # 状态
  state: State;
  # 停滞时间
  deadTime: Dead Time;Dead-Time;DeadTime
  # 地址
  address: Address;Area Id;Neighbor Ad
  # 端口号
  portNumber: Interface
  # BFD状态
  BFDState: BFD State
  # 间隔字符   例(端口号:GigabitEthernet 9/2中间存在空格)
  ospfSpaceCharacter: GigabitEthernet


#光衰
光衰:
  # RX默认额定偏差
  rxRatedDeviation: 1
  # TX默认额定偏差
  txRatedDeviation: 0.5
  #针对具体品牌
  H3C:
    获取端口号命令: display interface brief
    # 端口号用汉字：端口号替代，程序中会用真实获取到的端口号名替换汉字端口号
    获取光衰参数命令: display transceiver diagnosis interface 端口号
    # 这种判断光衰问题的方法已经放弃，但程序仍然保留
    阈值: [-23,-5]
    # 转译是命令要求用GigabitEthernet,但程序中获取到的是GE，需要将GE替换成GigabitEthernet
    转译:
      GE: GigabitEthernet
  RuiJie:
    获取端口号命令: show interface status
    获取光衰参数命令: show interface 端口号 transceiver diagnosis
    阈值: [-23,-5]
    转译:
      GE: GigabitEthernet
  HuaWei:
    获取端口号命令: display interface brief
    获取光衰参数命令: display transceiver interface 端口号 verbose
    阈值: [-23,-5]
    转译:
      GE: GigabitEthernet

#查看交换机错误包数量
误码率:
  H3C:
    # 端口号用汉字：端口号替代，程序中会用真实获取到的端口号名替换汉字端口号
    获取端口号命令: display interface brief
    获取误码率参数命令: display interface 端口号
    # 转译是命令要求用GigabitEthernet,但程序中获取到的是GE，需要将GE替换成GigabitEthernet
    转译:
      GE: GigabitEthernet
  RuiJie:
    获取端口号命令: show interface status
    获取误码率参数命令: show interface 端口号
    转译:
      GE: GigabitEthernet
  HuaWei:
    获取端口号命令: display interface brief
    获取误码率参数命令: display interface 端口号
    转译:
      GE: GigabitEthernet
  HuaWei路由器: display interface 端口号
  MaiP: show interface 端口号 statistics
  Cisco: show interfaces 端口号