# 配置
configuration:
  #自定义分隔符
  customDelimiter: "=:="
  # 最小超时
  minimumTimeout: 10000
  # 最大超时
  maximumTimeout: 60000
  # 循环次数
  numberOfCycles: 10
  # 标识符  两个标识符之间以;分阁
  identifier: (TM);®
  # 日志路径
  logPath: "D:\\jhnwadminlog"
  # 定时任务路径
  timedTaskPath: "D:\\jhnwadminlog\\交换机信息模板.xlsx"

#获取交换机基本信息
BasicInformation:
  # 获取交换机品牌的命令
  getBrandCommand: show version;display version
  # 获取交换机设备版本的关键字,默认关键字的下一位为要取的参数
  deviceVersion: software version;Version
  # 获取交换机设备子版本的关键字,默认关键字的下一位为要取的参数,两个关键字之间以;分隔
  deviceSubversion: RELEASE SOFTWARE;Release;Build
  # 等价  有的交换机品牌名 叫做 Huawei 同时也叫做  Quidway
  equivalence:
    Huawei: Quidway

#OSPF
OSPF:
  # neighborID、pri、state、deadTime、address、portNumber、BFDState
  # 这些属性是为了区分OSPF命令返回信息中的参数值
  # 邻居ID
  neighborID: Neighbor ID;Router ID
  # pri暂未使用，为占位列
  pri: Pri;
  # 状态
  state: State;
  # 停滞时间
  deadTime: Dead Time;Dead-Time;DeadTime
  # 地址
  address: Address;Area Id;Neighbor Ad
  # 端口号
  portNumber: Interface
  # BFD状态
  BFDState: BFD State
  # 间隔字符   例(端口号:GigabitEthernet 9/2中间存在空格)
  ospfSpaceCharacter: GigabitEthernet

#光衰
光衰:
  # RX默认额定偏差
  rxRatedDeviation: 1
  # TX默认额定偏差
  txRatedDeviation: 0.5
  # RX即时偏差
  rxImmediateDeviation: 0.5
  # TX即时偏差
  txImmediateDeviation: 0.3

# 端口号
obtainPortNumber:
  #获取端口号关键词
  keyword:
    GigabitEthernet
    GE
    FastEthernet
    Ten-GigabitEthernet
    Ethernet
    Eth-Trunk
    XGigabitEthernet
    Trunking
    BAGG
    Eth
    FastEthernet
    SFP
    USB

# 误码率
# 截取参数关键字应注意精确度，防止提取到多个数值，导致提取失败或提取数值错误
误码率:
  # 两个关键字之间以;分隔
  描述: Description
  H3C:
    Input: 'Input: $ input errors'
    Output: $ output errors
    CRC: $ CRC,
  Huawei:
    CRC: 'CRC: $'
    Input: 'Total Error: $'
    Output: 'Total Error: $'
  RuiJie:
    Input: $ input errors
    Output: $ output errors
    CRC: $ CRC,
  Maip:
    Input: 'RxErrorPkts : $'
    Output: 'TxErrorPkts : $'
  Cisco:
    Input: $ input errors
    Output: $ output errors