# 配置
configuration:
  #问题编码
  problemCode:
    #安全配置
    安全配置: SCRT
    #运行分析
    运行分析: OPSA
    #日常巡检
    日常巡检: DICA
  #地区编码
  regionalCode: 0001
  #自定义分隔符
  customDelimiter: "=:="
  # 最小超时
  minimumTimeout: 10000
  # 最大超时
  maximumTimeout: 60000
  # 循环次数
  numberOfCycles: 10
  # 标识符  两个标识符之间以;分阁
  identifier: (TM);®
  # 日志路径
  logPath: "D:\\jhnwadminlog"
  # 定时任务路径
  timedTaskPath: "D:\\jhnwadminlog\\交换机信息模板.xlsx"
  # 空间管理
  spaceManagement:
    # 数据保留时长(年)
    dataRetentionTime: 1
    # 所用空间占比(%)
    usedSpaceRate: 70
    # 自动空间管理周期（天）
    autoSpaceManagementCycle: 7

#获取交换机基本信息
BasicInformation:
  # 获取交换机品牌的命令
  getBrandCommand: show version;display version
  # 获取交换机设备版本的关键字,默认关键字的下一位为要取的参数
  deviceVersion: software version;Version
  # 获取交换机设备子版本的关键字,默认关键字的下一位为要取的参数,两个关键字之间以;分隔
  deviceSubversion: RELEASE SOFTWARE;Release;Build
  # 等价  有的交换机品牌名 叫做 Huawei 同时也叫做  Quidway
  equivalence:
    Huawei: Quidway

# 定时任务
TimedTasks:
  OSPF
  光衰
  错误包
  路由聚合
# 运行分析
运行分析:
  OSPF
  光衰
  错误包
  路由聚合

# 端口号
obtainPortNumber:
  #获取端口号关键词
  keyword:
    GigabitEthernet
    GE
    FastEthernet
    Ten-GigabitEthernet
    Ethernet
    Eth-Trunk
    XGigabitEthernet
    Trunking
    BAGG
    Eth
    FastEthernet
    SFP
    USB
    InLoop
    LoopBack
    Loop
    Vlan
    InLoopBack

#OSPF
OSPF:
  H3C:
    R_table:
      TableHeader: Area Id,Interface,Neighbor id,State
      address: Area Id
      portNumber: Interface
      neighborID: Neighbor id
      state: State

#光衰
光衰:
  # RX默认额定偏差
  rxRatedDeviation: 1
  # TX默认额定偏差
  txRatedDeviation: 0.5
  # RX即时偏差
  rxImmediateDeviation: 0.5
  # TX即时偏差
  txImmediateDeviation: 0.3
  percentage: 1%
  H3C:
    R_table:
      TableHeader: Temp(Celsius),Voltage(V),Bias(mA),RX power(dBm),TX power(dBm)
      RX: RX power(dBm)
      TX: TX power(dBm)
    L_list2:
      RX: 'Current Rx Power(dBM):$'
      TX: 'Current Tx Power(dBM):$'
    L_list1:
      RX: 'Rx Power:  $'
      TX: 'Tx Power:  $'


# 错误包
# 截取参数关键字应注意精确度，防止提取到多个数值，导致提取失败或提取数值错误
错误包:
  # 两个关键字之间以;分隔
  描述: Description
  percentage: 1%
  HuaWei:
    Input: 'Input: $ input errors'
    Output: $ output errors
    CRC: $ CRC,
  H3C:
    CRC: 'CRC: $'
    Input: 'Input \n5 Total Error: $'
    Output: 'Output \n4 Total Error: $'
    InputPKT:
      keyword: "Input: $1 bytes, $2 packets"
      InputPKT_PKT: $2
    OutputPKT:
      keyword: "Output: $1 bytes, $2 packets"
      OutputPKT_PKT: $2
  RuiJie:
    Input: $ input errors
    Output: $ output errors
    CRC: $ CRC,
  Maip:
    Input: 'RxErrorPkts : $'
    Output: 'TxErrorPkts : $'
  Cisco:
    Input: $ input errors
    Output: $ output errors

# 路由聚合
路由聚合:
  H3C:
    R_table:
      TableHeader: Destination/Mask,Proto,Pre,Cost,NextHop,Interface
      Destination/Mask: Destination/Mask
      protocol: Proto
      Pre_Def_priority: Pre
      Cost: Cost
      NextHop: NextHop
      Interface: Interface