# 配置
configuration:
  # 最小超时
  minimumTimeout: 10000
  # 最大超时
  maximumTimeout: 60000
  # 循环次数
  numberOfCycles: 10
  # 标识符
  identifier: (TM);®
  # 日志路径
  logPath: "D:\IdeaProjects\github\beifen\jhnwadminlog"